In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/models/debangshudey2004/gru-conv1d-model/keras/default/1/GRU_CONV1D_Model.keras
/kaggle/input/models/debangshudey2004/weightedsamplesbidirectionallstm-model/keras/default/1/WeightedSamplesBidirectionalLSTM_Model.keras
/kaggle/input/models/debangshudey2004/bidirectionallstm-model/keras/default/1/BidirectionalLSTM_Model.keras
/kaggle/input/models/debangshudey2004/densegru-conv1d-model/keras/default/1/DenseGRU_CONV1D_Model.keras
/kaggle/input/models/debangshudey2004/singlelstm-model/keras/default/1/SingleLSTM_Model.keras


In [2]:
import gdown 

url = "https://drive.google.com/file/d/1A40POUq1g1EqSlE76zqqyHo4KqzLVtub/view?usp=sharing"
output_filename = 'LogisticRegressionModel.pkl'

# Use fuzzy=True so gdown strips away the Google HTML warning pages
file_path = gdown.download(url, output_filename, quiet=False, fuzzy=True)

# Read the file now that it is properly saved on disk
LRModel = pd.read_pickle(file_path)

Downloading...
From: https://drive.google.com/uc?id=1A40POUq1g1EqSlE76zqqyHo4KqzLVtub
To: /kaggle/working/LogisticRegressionModel.pkl
100%|██████████| 97.4M/97.4M [00:01<00:00, 87.5MB/s]


In [3]:


import gdown 

url = "https://drive.google.com/file/d/1BhsF97-CgeZj5UDT5WozXC564KtaQ2WK/view?usp=sharing"
output_filename = 'LogisticVectorizer.pkl'

# Use fuzzy=True so gdown strips away the Google HTML warning pages
file_path = gdown.download(url, output_filename, quiet=False, fuzzy=True)

# Read the file now that it is properly saved on disk
LV = pd.read_pickle(file_path)

Downloading...
From: https://drive.google.com/uc?id=1BhsF97-CgeZj5UDT5WozXC564KtaQ2WK
To: /kaggle/working/LogisticVectorizer.pkl
100%|██████████| 56.4M/56.4M [00:00<00:00, 159MB/s] 


In [4]:
comments = [
    "I appreciate your help",
    "That was a very stupid thing to say",
    "You deserve to get hurt",
    "He is a Muslim teacher",
    "I hate Muslims",
    "Everybody secretly hates you",
    "He is black",
    "He is an annoying black dude",
    "She is a woman",
    "She is a nice woman",
    "She is not bad"
]

# Transform text
comments_tfidf = LV.transform(comments)

# Predict probabilities
pred_probs = LRModel.predict_proba(comments_tfidf)[:, 1]

# Convert to labels
pred_labels = (pred_probs >= 0.5).astype(int)

# Print results
for comment, prob, label in zip(comments, pred_probs, pred_labels):
    print(f"Comment: {comment}")
    print(f"Toxic Probability: {prob:.4f}")
    print(f"Prediction: {'Toxic' if label == 1 else 'Non-Toxic'}")
    print("-" * 60)

Comment: I appreciate your help
Toxic Probability: 0.0131
Prediction: Non-Toxic
------------------------------------------------------------
Comment: That was a very stupid thing to say
Toxic Probability: 0.9999
Prediction: Toxic
------------------------------------------------------------
Comment: You deserve to get hurt
Toxic Probability: 0.1427
Prediction: Non-Toxic
------------------------------------------------------------
Comment: He is a Muslim teacher
Toxic Probability: 0.8367
Prediction: Toxic
------------------------------------------------------------
Comment: I hate Muslims
Toxic Probability: 0.9850
Prediction: Toxic
------------------------------------------------------------
Comment: Everybody secretly hates you
Toxic Probability: 0.0791
Prediction: Non-Toxic
------------------------------------------------------------
Comment: He is black
Toxic Probability: 0.9996
Prediction: Toxic
------------------------------------------------------------
Comment: He is an annoying b

In [5]:
from tensorflow.keras.models import load_model

SingleLSTM_model = load_model('/kaggle/input/models/debangshudey2004/singlelstm-model/keras/default/1/SingleLSTM_Model.keras')

2026-06-04 15:44:22.519050: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1780587862.809420      57 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1780587862.889910      57 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1780587863.616080      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1780587863.616127      57 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1780587863.616130      57 computation_placer.cc:177] computation placer alr

In [6]:
import gdown
MAX_SEQUENCE_LENGTH = 300

url = "https://drive.google.com/file/d/15PWNsDqb-QFg34YQ90GUGnO9gi1YQEgs/view?usp=sharing"
output_filename = 'tokenizer.pkl'

# Use fuzzy=True so gdown strips away the Google HTML warning pages
file_path = gdown.download(url, output_filename, quiet=False, fuzzy=True)

# Read the file now that it is properly saved on disk
tokenizer = pd.read_pickle(file_path)



from tensorflow.keras.preprocessing.sequence import pad_sequences

def padding_text(texts):
    return pad_sequences(
        texts,
        maxlen=MAX_SEQUENCE_LENGTH
    )

Downloading...
From: https://drive.google.com/uc?id=15PWNsDqb-QFg34YQ90GUGnO9gi1YQEgs
To: /kaggle/working/tokenizer.pkl
100%|██████████| 12.7M/12.7M [00:00<00:00, 195MB/s]


In [7]:
comments = [
    "I appreciate your help",
    "That was a very stupid thing to say",
    "You deserve to get hurt",
    "He is a Muslim teacher",
    "I hate Muslims",
    "Everybody secretly hates you",
    "He is black",
    "He is an annoying black dude",
    "She is a woman",
    "She is a nice woman",
    "She is not bad"
]

for sentence in comments:

    seq = tokenizer.texts_to_sequences([sentence])

    padded = pad_sequences(
        seq,
        maxlen=MAX_SEQUENCE_LENGTH
    )

    pred = SingleLSTM_model.predict(padded, verbose=0)

    print(sentence)
    print(pred)
    print("-"*50)

I appreciate your help
[[0.9984884  0.00151153]]
--------------------------------------------------
That was a very stupid thing to say
[[0.00671319 0.9932868 ]]
--------------------------------------------------
You deserve to get hurt
[[0.97264177 0.02735826]]
--------------------------------------------------
He is a Muslim teacher
[[0.66305715 0.3369428 ]]
--------------------------------------------------
I hate Muslims
[[0.698      0.30200002]]
--------------------------------------------------
Everybody secretly hates you
[[0.9426953  0.05730466]]
--------------------------------------------------
He is black
[[0.93852943 0.06147061]]
--------------------------------------------------
He is an annoying black dude
[[0.33499658 0.66500336]]
--------------------------------------------------
She is a woman
[[0.8373635 0.1626365]]
--------------------------------------------------
She is a nice woman
[[0.91789734 0.08210266]]
--------------------------------------------------
She is

In [8]:
BidirectionalLSTM_model = load_model('/kaggle/input/models/debangshudey2004/bidirectionallstm-model/keras/default/1/BidirectionalLSTM_Model.keras')

In [9]:
comments = [
    "I appreciate your help",
    "That was a very stupid thing to say",
    "You deserve to get hurt",
    "He is a Muslim teacher",
    "I hate Muslims",
    "Everybody secretly hates you",
    "He is black",
    "He is an annoying black dude",
    "She is a woman",
    "She is a nice woman",
    "She is not bad"
]


for sentence in comments:

    seq = tokenizer.texts_to_sequences([sentence])

    padded = pad_sequences(
        seq,
        maxlen=MAX_SEQUENCE_LENGTH
    )

    pred = BidirectionalLSTM_model.predict(padded, verbose=0)

    print(sentence)
    print(pred)
    print("-"*50)

I appreciate your help
[[0.985025   0.01497503]]
--------------------------------------------------
That was a very stupid thing to say
[[0.00165142 0.9983486 ]]
--------------------------------------------------
You deserve to get hurt
[[0.4590601 0.54094  ]]
--------------------------------------------------
He is a Muslim teacher
[[0.59578234 0.40421766]]
--------------------------------------------------
I hate Muslims
[[0.2180193 0.7819807]]
--------------------------------------------------
Everybody secretly hates you
[[0.20420513 0.79579484]]
--------------------------------------------------
He is black
[[0.46846384 0.5315362 ]]
--------------------------------------------------
He is an annoying black dude
[[0.06520987 0.9347902 ]]
--------------------------------------------------
She is a woman
[[0.8897523  0.11024773]]
--------------------------------------------------
She is a nice woman
[[0.9409286  0.05907146]]
--------------------------------------------------
She is n

In [10]:
WSBLSTM_model = load_model('/kaggle/input/models/debangshudey2004/weightedsamplesbidirectionallstm-model/keras/default/1/WeightedSamplesBidirectionalLSTM_Model.keras')

In [11]:
comments = [
    "I appreciate your help",
    "That was a very stupid thing to say",
    "You deserve to get hurt",
    "He is a Muslim teacher",
    "I hate Muslims",
    "Everybody secretly hates you",
    "He is black",
    "He is an annoying black dude",
    "She is a woman",
    "She is a nice woman",
    "She is not bad"
]

for sentence in comments:

    seq = tokenizer.texts_to_sequences([sentence])

    padded = pad_sequences(
        seq,
        maxlen=MAX_SEQUENCE_LENGTH
    )

    pred = WSBLSTM_model.predict(padded, verbose=0)

    print(sentence)
    print(pred)
    print("-"*50)

I appreciate your help
[[0.9843911 0.0156089]]
--------------------------------------------------
That was a very stupid thing to say
[[7.240253e-04 9.992760e-01]]
--------------------------------------------------
You deserve to get hurt
[[0.47789425 0.52210575]]
--------------------------------------------------
He is a Muslim teacher
[[0.5773952  0.42260477]]
--------------------------------------------------
I hate Muslims
[[0.13862592 0.8613741 ]]
--------------------------------------------------
Everybody secretly hates you
[[0.15469389 0.8453061 ]]
--------------------------------------------------
He is black
[[0.29620185 0.7037981 ]]
--------------------------------------------------
He is an annoying black dude
[[0.01543107 0.98456895]]
--------------------------------------------------
She is a woman
[[0.8185462  0.18145381]]
--------------------------------------------------
She is a nice woman
[[0.93186194 0.06813808]]
--------------------------------------------------
Sh

In [12]:
from tensorflow.keras.layers import Layer
from tensorflow.keras import backend as K
from tensorflow.keras import initializers, regularizers, constraints

import tensorflow as tf
class Attention(Layer):
    def __init__(self, step_dim,
                 W_regularizer=None, b_regularizer=None,
                 W_constraint=None, b_constraint=None,
                 bias=True, **kwargs):
        self.supports_masking = True
        self.init = initializers.get('glorot_uniform')

        self.W_regularizer = regularizers.get(W_regularizer)
        self.b_regularizer = regularizers.get(b_regularizer)

        self.W_constraint = constraints.get(W_constraint)
        self.b_constraint = constraints.get(b_constraint)

        self.bias = bias
        self.step_dim = step_dim
        self.features_dim = 0
        super(Attention, self).__init__(**kwargs)

    def build(self, input_shape):
        assert len(input_shape) == 3

        self.W = self.add_weight((input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_W'.format(self.name),
                                 regularizer=self.W_regularizer,
                                 constraint=self.W_constraint)
        self.features_dim = input_shape[-1]

        if self.bias:
            self.b = self.add_weight((input_shape[1],),
                                     initializer='zero',
                                     name='{}_b'.format(self.name),
                                     regularizer=self.b_regularizer,
                                     constraint=self.b_constraint)
        else:
            self.b = None

        self.built = True

    def compute_mask(self, input, input_mask=None):
        return None

    def call(self, x, mask=None):
        features_dim = self.features_dim
        step_dim = self.step_dim
    
        # Replace K.reshape + K.dot with TensorFlow ops
        eij = tf.reshape(
            tf.matmul(
                tf.reshape(x, (-1, features_dim)),
                tf.reshape(self.W, (features_dim, 1))
            ),
            (-1, step_dim)
        )
    
        if self.bias:
            eij += self.b
    
        eij = tf.tanh(eij)
    
        a = tf.exp(eij)
    
        if mask is not None:
            a *= tf.cast(mask, tf.float32)
    
        a /= tf.cast(
            tf.reduce_sum(a, axis=1, keepdims=True) + K.epsilon(),
            tf.float32
        )
    
        a = tf.expand_dims(a, axis=-1)
    
        weighted_input = x * a
    
        return tf.reduce_sum(weighted_input, axis=1)

    def compute_output_shape(self, input_shape):
        return input_shape[0],  self.features_dim

In [13]:
GRU_CONV1D_model = load_model(
    '/kaggle/input/models/debangshudey2004/gru-conv1d-model/keras/default/1/GRU_CONV1D_Model.keras',
    custom_objects={'Attention': Attention}
)

In [14]:
comments = [
    "I hope you have a wonderful day",
    "You are being annoying",
    "You are a complete idiot",
    "I will destroy your life",
    "You are a fucking loser",
    "He is a Muslim man",
    "Great job ruining everything"
]

comments = [
    "I appreciate your help",
    "That was a very stupid thing to say",
    "Nobody wants you here",
    "You deserve to get hurt",
    "Wow, brilliant move genius",
    "He is a Muslim teacher",
    "I hate Muslims",
    "You murdered that presentation",
    "Cry more kid",
    "Everybody secretly hates you"
]

for sentence in comments:

    seq = tokenizer.texts_to_sequences([sentence])

    padded = pad_sequences(
        seq,
        maxlen=MAX_SEQUENCE_LENGTH
    )

    pred = GRU_CONV1D_model.predict(padded, verbose=0)

    print(sentence)
    print(pred)
    print("-"*50)

I appreciate your help
[[0.9988175  0.00118249]]
--------------------------------------------------
That was a very stupid thing to say
[[0.01358472 0.9864153 ]]
--------------------------------------------------
Nobody wants you here
[[0.9982963  0.00170372]]
--------------------------------------------------
You deserve to get hurt
[[0.91187876 0.08812124]]
--------------------------------------------------
Wow, brilliant move genius
[[0.9966736  0.00332643]]
--------------------------------------------------
He is a Muslim teacher
[[0.7763377  0.22366238]]
--------------------------------------------------
I hate Muslims
[[0.1679914 0.8320086]]
--------------------------------------------------
You murdered that presentation
[[0.84065706 0.15934294]]
--------------------------------------------------
Cry more kid
[[0.95500064 0.04499942]]
--------------------------------------------------
Everybody secretly hates you
[[0.9012368  0.09876321]]
----------------------------------------

In [15]:
DenseGRU_CONV1D_model = load_model(
    '/kaggle/input/models/debangshudey2004/densegru-conv1d-model/keras/default/1/DenseGRU_CONV1D_Model.keras')

In [16]:
comments = [
    "I hope you have a wonderful day",
    "You are being annoying",
    "You are a complete idiot",
    "I will destroy your life",
    "You are a fucking loser",
    "He is a Muslim man",
    "Great job ruining everything"
]

comments = [
    "I appreciate your help",
    "That was a very stupid thing to say",
    "Nobody wants you here",
    "You deserve to get hurt",
    "Wow, brilliant move genius",
    "He is a Muslim teacher",
    "I hate Muslims",
    "You murdered that presentation",
    "Cry more kid",
    "Everybody secretly hates you"
]

for sentence in comments:

    seq = tokenizer.texts_to_sequences([sentence])

    padded = pad_sequences(
        seq,
        maxlen=MAX_SEQUENCE_LENGTH
    )

    pred = DenseGRU_CONV1D_model.predict(padded, verbose=0)

    print(sentence)
    print(pred)
    print("-"*50)

I appreciate your help
[[0.9987205  0.00127955]]
--------------------------------------------------
That was a very stupid thing to say
[[0.00528486 0.99471515]]
--------------------------------------------------
Nobody wants you here
[[0.9971455  0.00285449]]
--------------------------------------------------
You deserve to get hurt
[[0.938235   0.06176506]]
--------------------------------------------------
Wow, brilliant move genius
[[0.99555236 0.00444758]]
--------------------------------------------------
He is a Muslim teacher
[[0.7154088  0.28459123]]
--------------------------------------------------
I hate Muslims
[[0.06249208 0.9375079 ]]
--------------------------------------------------
You murdered that presentation
[[0.6828869 0.3171131]]
--------------------------------------------------
Cry more kid
[[0.96065485 0.03934513]]
--------------------------------------------------
Everybody secretly hates you
[[0.88261235 0.11738763]]
----------------------------------------